language: python
sudo: false
branches:
  only:
    - master
python:
  - "2.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --yes conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=2.7 nose numpy scipy pytables pycrypto twisted serial
  - git clone https://bitbucket.org/tainstr/misura.canon.git ../misura.canon
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/../misura.canon
script:
  - source activate test-environment
  - pip install python-coveralls
  - nosetests --with-coverage --cover-package=misura.droid
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
after_success:
  - coveralls
